project:
  type: website
  output-dir: _site
  
date: today
date-format: "YYYY"

website:
  title: "Automating Metagenomics Analyses with Bash Scripts"
  page-footer:
    left: |
      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2021–{{<meta date>}} by [Cloud-SPAN](https://cloud-span.york.ac.uk/)\
      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2018–{{<meta date>}} by the [Carpentries](https://carpentries.org/)\
      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2016–2018 by the [Data Carpentry](https://datacarpentry.org/)      
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: Quarto Blog RSS
  navbar:
    background: light
    logo: images/cloud-span-icon.png
    logo-alt: "Cloud-SPAN logo."
    title: false
    collapse-below: lg
    left:
      - text: Home  
        href: index.qmd
      - text: Lessons
        href: docs/navbar/lessons.qmd
      - text: Setup
        href: docs/navbar/setup.qmd
      - text: Extras
        href: docs/navbar/extras.qmd
      - text: License
        href: docs/navbar/license.qmd
      - text: Code of Conduct
        href: docs/navbar/codeofconduct.qmd
      - text: Help
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/quarto-dev/quarto-cli/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/quarto-dev/quarto-cli/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: docs/faq/index.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



